---
title: "Research on Labor Market Participation Based on Sex"
author: 
  - NAGHIYEVA, Malak [^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080159, [Github Repo](https://github.com/MelekNaghi/Midterm.git)


# Introduction
The labor market is a gendered institution, and even if education levels are the same, labor force participation is biased against one gender. Feminist economists criticize mainstream economics and argue that the market structure remains gendered, despite the decreasing gender wage gap. In addition, factors such as age, marital status, and area of living influence employment status, with women having fewer opportunities to commute or relocate.

The research aims to address the question of whether the market system is a gendered institution that creates mass inequality in labor force participation. To investigate this phenomenon, the study will examine whether factors such as marital status, age, and area of living affect women more than men. The study will also compare the sex ratio of the labor force based on educational level.

The study will use three data sets from ILO, supplemented by relevant literature. All sources will be cited in the references section.

## Literature Review

Mainstream economics view labor markets as neutral arenas that focus solely on efficient production. However, feminist economists argue that this approach creates unequal empowerment between men and women due to two reasons. Firstly, even though the labor markets themselves do not create unequal opportunities within society, the unequal system boosts efficiency, therefore nurturing markets [@elson1999labor]. Secondly, from a feminist perspective, it is a prominent issue that, even though labor force participation has increased in developing countries, most of the women's participation belongs to export-oriented sectors with less stable and long-term jobs, creating further inequalities [@ngai2007gendering].

Women's force participation is vital for economic development. It is observed that the Middle East and North Africa regions have made progress in gender participation in education in the last four decades [@assaad2020explaining]. When economic development is considered to increase the total welfare without worsening anyone which is called harmonizing up, women's labor force participation tends to increase. Unfortunately, this relationship is not consistent and may empower men more than women, resulting in an inconsistent improvement in overall welfare [@verick2014female].





\newpage
# References {#references}
<div id="refs"></div>



